### ISSUE TITLE
Confusion in data of "Countries UN operates in" count against "Compare countries" count

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/UN-Transparency-Portal#111]
For the homepage, when we list countries we check for country's code and text. These codes and texts are pulled from iati's code list. However countries in homepage are verified according to the iati list  and  in the compare countries page data are pulled from database. In the compare countries page there are country codes (such as REG-EUROPE-CENTRAL-ASIA, SREG-CARIB-ENGLISH-DUTCH) which are not listed as country in iati's code list. Should we count them as countries as well for "Countries UN operates in" section?

**Comment by abdulriza** [comment]
@bezunakarmi No, we will not count them as countries in 'countries UN operates in' section. We will implement the same for 'compare all countries page' in order to be consistent. Also, as we discussed, let's have the rest of all regional and global projects listed under one item ' Regional and global' but we don't have to add this to the number of countries in the stats.

**Comment by bezunakarmi** [comment]
This has been done.Please do check.
