### ISSUE TITLE
Agency page budget table is not showing the budget amount for UNOCHA

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#134]
@anjesh @bezunakarmi UNOCHA is showing 515 M total budget but the table does not include any budget amount for any year. The xml does have budget and recipient countries - Example: http://188.166.155.208/ctrack.html?publisher=41127&tongue=eng#view=act&aid=41127-N527-FY2015

**Comment by bezunakarmi** [comment]
@abdulriza For UNOCHA the issue with showing the budget on the "[Where does the money come from ](http://open.undg.org/ctrack.html?publisher=41127&tongue=eng#view=donors)" table doesn't show any budget. In this table there are 2 sections "IATI Spend" and "IATI Budget", the spend section shows the transaction which have either disbursement or expenditure but UNOCHA has transactions for Incoming fund only. Therefore the spend budget is not shown.

And in the budget section, the d-portal's script shows the budget that has budget priority 1 where in UNOCHA the budget priority is set to 0. This is because the budget date for UNOCHA activities have same budget start and end dates.
`<budget type="1">
      <period-start iso-date="2014-12-31">01/01/2014</period-start>
      <value currency="USD" value-date="2014-01-01">1928792</value>
      <period-end iso-date="2014-12-31">31/12/2014</period-end>
    </budget>`
So, what the script does is it takes the iso-date of the budget start and end dates and calculates the budget length. If the budget length is 0 then it initializes the budget priority to 0.

So, what can be done to fix this is either we don't show the budget which has priority 0 in the agency detail page or we give priority to budget priority 1 on this section and if there is no budget in priority 1 then we take budget priority 0.

So, please do have a look at it.

**Comment by bezunakarmi** [comment]
@abdulriza should we close this issue.
