### ISSUE TITLE
UNCDF aggregation is wrong - urgent

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#172]
@anjesh @bezunakarmi The aggregated numbers showing for UNCDF is wrong. The portal shows 402 projects but their xml file has only 132 activities. The total expenditure is also wrong which should be around 70M. It looks like the portal is reading from an old file also as I can see that activities are duplicated in the list. 

Can you check and correct urgently.

**Comment by bezunakarmi** [comment]
@abdulriza, it took time for us to address this issue, we apologize for that. 
The issue we had was due to old xml files from UNCDF. We have cleared all the old xml files. The total number of Project that you can see in the portal is 118 and in https://iatiregistry.org/publisher/uncdf we can see it has 142 activities. Among these we have 8 activity that has duplicate iati-identifier which has been neglected by the storing script. Those identifiers are:
- 93772
- 90703
- 88644
- 90014
- 94985
- 93466
- 95554
- 88975

Please do let us know if there are any other issues.

**Comment by abdulriza** [comment]
@bezunakarmi @anjesh Thanks. It looks UNCDF is corrected but the entire portal is messed up. The portal doesn't show data from 6 organizations Worldbank, WPF, OCHA, UNOPS, UN Women and UNITAID. I am bit concerned and expect little more effective validation process to ensure the accuracy of the data presented. I would appreciate **URGENT** attention to this and make sure all in order.

**Comment by bezunakarmi** [comment]
Apologies for the inconvenience, the issue that you pointed out has been solved. There were data from the publishers that you mentioned, but links were disabled in the homepage.
