### ISSUE TITLE
Add WHO data to the portal

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#173]
@anjesh @bezunakarmi WHO has started publishing to IATI and we can now activate WHO on the portal to add their data to the portal visualization.

**Comment by bezunakarmi** [comment]
@abdulriza WHO has been added an IATI publisher in the portal.
![screen shot 2017-06-14 at 1 09 32 pm](https://user-images.githubusercontent.com/12218329/27120831-c65c6b4c-5104-11e7-8c96-9e865c5fae7d.png)

![screen shot 2017-06-14 at 1 15 24 pm](https://user-images.githubusercontent.com/12218329/27120833-c8a0a3dc-5104-11e7-954f-5683c7d9c934.png)


Also, we found out that **International Fund for Agricultural Development (IFAD)** IATI publisher ID has been changed from **41108** to **XM-DAC-41108**. Due to wich IFAD was disabled from the list of UN Publishers. This issue has also been solved.
![screen shot 2017-06-14 at 1 26 26 pm](https://user-images.githubusercontent.com/12218329/27120947-1ba96d70-5105-11e7-8515-6bad9ae2c752.png)
