### ISSUE TITLE
Homepage design/ mockup

### ISSUE THREAD

**Issue by anjhero** [younginnovations/UN-Transparency-Portal#2]
Homepage should include following:

- Navigation for about, explore and generator
- Summary stats at the top (including Total number of projects, Total budget, Total expenditure, Total number of UN agencies publishing to IATI, Total number of countries UN operates, Budget % comparison of total UN vs other organisation)
- List of UN agencies with their names and logos. Each of these list item will be linked to their transparency portal pages. Agencies with no transparency portals will be linked to their corporate website (if they have one). 
- CTA (Call To Action) button - Compare all publishers 
- CTA button - Compare all countries
- CTA button - Compare all sectors
- List of all countries

**Comment by anjhero** [comment]
Here's a very initial mockup of the homepage based on the specifications in TOR. 
![un transparency portal](https://cloud.githubusercontent.com/assets/528549/13351816/71631c1c-dcb1-11e5-8492-7ea953cdf198.png)

**Comment by anjesh** [comment]
@abdulriza to get back with feedbacks on the homepage design.

**Comment by mariablancolora** [comment]
Dear All,

I am sharing here the meeting minutes from the last meeting. 

**UNDG Transparency Portal will be the name of the microsite.**
-       Maria to share UNDG logo in vector format with Young Innovation.
-       The url will be opendata.undg.org
 
**Data visualization section:**
-       The proposed data visualization on the home page is accepted. However, we need to find content for the box 5. The data currently displayed doesn’t reflect relevant information.
 
**Participating agencies section:**
The name of this section should be changed to UNDG Members and Observers.
The heading should embed an hyperlink to the following page: https://undg.org/home/about-undg/members/
Logos of the organizations will be the access point on the home page for the data per agency. The information in the dportal will be the one displayed in the agency page.
The UN organizations that are publishing through IATI will be the first ones to be displayed. The order to display the logos will be arranged by volume. 
The UNDG members and observers that don’t have data will be still placed on the home page but as a watermark. 
Place an ALT message to be displayed on the images of the agencies that don’t have data to explain that data related to the agency/fund/programme is not available yet.
Maria to confirm the logos and the names of agencies to be displayed in this section.

**Section on countries and sectors:**
The list of countries and sectors to be displayed will be reduced to 10.
We need to create a sector page. We are suggesting to create something similar to the design of the countries. The background color has to be changed. 
For the sector one, Riza will reply to the developers
Hosting be done by young innovation and also a maintenance for a year.
 
**SDG logos** to be displayed at the end of the page: We will display the SDG logos with no link (the way is displayed currently on the undg.org site). Once the data is available, we will make the logos clickable.

**Comment by anjhero** [comment]
I'm creating new issues for some of the ones listed above. I'm closing this issue page.

**Comment by mariablancolora** [comment]
ABOUT PAGE -TEXT

UNDG Transparency Portal
The International Aid Transparency Initiative (IATI) is a voluntary, multi-stakeholder initiative that seeks to improve the transparency of aid, development, and humanitarian resources in order to increase their effectiveness in tackling poverty. IATI brings together donor and recipient countries, civil society organizations, and other experts in aid information who are committed to working together to increase the transparency and openness of aid. At the center of IATI is the IATI Standard, a format and framework for publishing data on development cooperation activities, intended to be used by all organizations in development, including government donors, private sector organizations, and national and international NGOs. It was designed in close consultation with key users of development cooperation data in developing countries, to ensure its relevance and utility for a variety of different data users.[1] 
 
In 2011, at the Fourth High Level Forum on Aid Effectiveness in Busan, Korea, the United Nations Development Group (UNDG) endorsed the Busan Partnership for Effective Development Co-operation. Paragraph 23(c) encourages its signatories to publish data according to IATI standard. An increasing number of UNDG members and observers are now publishing data and joining IATI as members.
 
How to use the Portal
The portal displays data of all UNDG members that are currently publishing data as per the IATI standard. The data is updated in real time by pulling data from the IATI registry (http://www.d-portal.org/), the central data store gathering all data published to the IATI standard.  This portal is meant to be a way for our partners to see all UNDG related data in one place. Data can be displayed by country, UN agency or sector.

**Comment by anjhero** [comment]
This issue is closed. I'm copy/pasting the About content to [this issue](https://github.com/younginnovations/UN-Transparency-Portal/issues/9)

**Comment by mariablancolora** [comment]
All logos for the IATI site can be dowloaded from the following link:

https://drive.google.com/file/d/0BwoAm3ycE5n2anVtNUl2T2VNWjQ/view?usp=sharing

**Comment by anjhero** [comment]
Thank you @mariablancolora . But we could access only one logo (UNWTO's) from the link you sent.

**Comment by mariablancolora** [comment]
Apologies for this
Find the new link below, where you can find all the logos as well as the UNDG logo

https://drive.google.com/folderview?id=0BwoAm3ycE5n2Y2RyTXRuTUJoOWs&usp=sharing

**Comment by mariablancolora** [comment]
Dear Anjan,


I have included another link with all the logos.


https://drive.google.com/folderview?id=0BwoAm3ycE5n2Y2RyTXRuTUJoOWs&usp=sharing


sorry about this.


best,

maria


________________________________
De: Anjan Shrestha <notifications@github.com>
Enviado: jueves, 24 de marzo de 2016 0:00
Para: younginnovations/UN-Transparency-Portal
Cc: Maria Blanco
Asunto: Re: [UN-Transparency-Portal] Homepage design/ mockup (#2)


Thank you @mariablancolora<https://github.com/mariablancolora> . But we could access only one logo (UNWTO's) from the link you sent.

-

**Comment by anjhero** [comment]
Thanks @mariablancolora
