### ISSUE TITLE
List of UN agencies without their logos

### ISSUE THREAD

**Issue by puzzz21** [younginnovations/UN-Transparency-Portal#58]
1. UNDP
2. CERF
3. UNCDF
4. UNH
5. UNECLAC
6. UNWTO
7. UNCDF
8. UNRISD
9. OCHA
10. UNITAID
11. WB
12. OHCHR
13. UNESCAP
14. DSG
15. UNDPI
16. UNSSC
17. OHRLLS
18. OSAA
19. UNECA
20. UNESCWA
21. ITC
22. UNICRI
23. UNU
24. UNV

**Comment by abdulriza** [comment]
@puzzz21 You haven't received the logos yet?

**Comment by anjhero** [comment]
Hi @abdulriza, yes we've received the logos. This issue was for our internal workflow check where all of the logos were not uploaded to the transparency portal yet. All of the logos will be uploaded to the portal by today. 

However, we do have some image quality issues with some of the logos. Is it possible to send all logos in vector format?
