### ISSUE TITLE
Number of agencies reporting 

### ISSUE THREAD

**Issue by mariablancolora** [younginnovations/UN-Transparency-Portal#87]
The total number of agencies reporting is 27. Here are the names:

[Final-UN-Agencies-reporting.xlsx](https://github.com/younginnovations/UN-Transparency-Portal/files/228610/Final-UN-Agencies-reporting.xlsx)

**Comment by anjesh** [comment]
I am guessing you are getting these data from [iatistandard codelist](http://iatistandard.org/202/codelists/OrganisationIdentifier/). However all of them are not yet publishers. They should be listed in registry http://iatiregistry.org/publisher before they could be queried for their projects data. Please see the agencies which have data in the iatiregistry.org and those who are not yet publishers. There are two agencies at the bottom - which seems to be part of UN agencies but they are not listed in the codelist. They are also included in the portal. 

![image](https://cloud.githubusercontent.com/assets/120488/14739652/b3b1e300-08a8-11e6-9658-ad6875ec0635.png)

**Comment by anjhero** [comment]
Please check @mariablancolora @abdulriza

**Comment by mariablancolora** [comment]
Thanks! I will share it with Gina and get back to you.

**Comment by abdulriza** [comment]
@anjhero @anjesh Sorry for the confusion. The list @mariablancolora shared was the full list of organizations to appear under 'UNDG members and observers' (not reporting). Accordingly, 27 will be the number (instead of 49) to appear on the homepage as the total number of agencies. We can remove the rest of the organizations in the list.
